### ISSUE TITLE
Unknown typename 'loff_t'

### ISSUE THREAD

**Issue by kfiros** [dtrugman/pfs#13]
I get this error (when including <pfs/procfs.hpp>):
error: unknown type name 'loff_t';
      did you mean 'off_t'?
    std::vector<uint8_t> read(loff_t offset, size_t len);
in mem.hpp.

I think we should fix it as done here:
https://github.com/nwchemgit/nwchem/commit/492f2661105ef5914fe9c3df4b6c74232bac0dd2

What do you think?

**Comment by dtrugman** [comment]
I replaced `off_t` with `loff_t` because otherwise, on 32-bit systems, one cannot access the entire address space - [link to commit](https://github.com/dtrugman/pfs/pull/10/commits/757d2c00afc2d6a8510cdf1131ad7acdcf3ba65d).

According to this [GNU manual](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html) it says:
_"This macro should only be selected if the system provides mechanisms for handling large files"_
...
_"This macro was introduced as part of the Large File Support extension (LFS)"_

A quick search shows that there are still some issues with that:
[Issue #1](https://lwn.net/Articles/590815/) - Now `preadv` can accept a 64-bit `off_t`, but the return value is `ssize_t`, which is still a 32-bit variable.

Seems to me like an include issue. I looked at the code and I think we should move
```
#include <fcntl.h>
#include <sys/types.h>
```

From `mem.cpp` to `mem.hpp`. Can you check if that solves the issue?

**Comment by kfiros** [comment]
It solves the issue.
